# -*- coding: utf-8 -*-
"""Auto-generated by scripts/build_mschema.py — do not edit by hand."""

MSCHEMA = r'''【DB_ID】 fahmai   (Supabase Postgres — prefer the v_* views)

# Table: v_sales  (1 row/txn, deduped; enriched (branch/customer/fiscal_year_ce))
[
  (txn_id:TEXT, PK, ex:[TXN-202401-01000002, TXN-202401-01000422, TXN-202401-01000462])
  (business_event_date:DATE, ex:[2025-11-24, 2025-03-31, 2025-02-16])
  (posting_date:DATE, ex:[2025-11-24, 2025-03-31, 2025-02-16])
  (effective_date:DATE)
  (as_of_date:DATE, ex:[2026-01-15])
  (branch_code:TEXT, -> dim_branch.branch_code, ex:[CNX-MAYA, BKK-CTW, HKT-FEST])
  (customer_id:TEXT, -> dim_customer.customer_id, ex:[CUST-L3-000057, CUST-L3-B2B-006800, CUST-L3-B2B-011800])
  (employee_id:TEXT, -> dim_employee.employee_id, ex:[EMP-L3-00011, EMP-L3-00002])
  (channel:TEXT, ex:[online, offline, b2b])
  (basket_total_thb:NUMERIC(14,2), ex:[239600.00, 379900.00, 298200.00])
  (discount_total_thb:NUMERIC(14,2), ex:[5364.00, 40092.00, 4932.00])
  (net_total_thb:NUMERIC(14,2), ex:[239600.00, 379900.00, 20640.00])
  (shipping_charge_thb:NUMERIC(14,2), ex:[0.00])
  (shipping_method:TEXT, ex:[enterprise_fleet, standard, express])
  (promo_campaign_id:TEXT, -> dim_promo_campaign.campaign_id, ex:[MEGA-1111-2567, MEGA-1111-2568, CLEAR-EOY-2568])
  (payment_method:TEXT, ex:[net_30, bank_transfer, mobile_wallet])
  (payment_status:TEXT, ex:[pending, paid])
  (payment_due_date:DATE, ex:[2025-07-31, 2025-02-18, 2026-01-13])
  (payment_received_date:DATE, ex:[2025-11-24, 2025-03-31, 2025-02-16])
  (settlement_bank_txn_id:TEXT, ex:[BT-202404-553323239810, BT-202408-199251231450, BT-202407-323436066009])
  (web_log_line_id:TEXT, ex:[web_20250422.jsonl:line18, web_20240705.jsonl:line6, web_20250306.jsonl:line84])
  (schema_version:INT, ex:[2, 1])
  (is_b2b:BOOL, ex:[False, True])
  (retry_idempotency_marker:TEXT)
  (fiscal_year:INT, ex:[2568, 2567])
  (fiscal_year_ce:INT, ex:[2024, 2025])
  (fiscal_quarter:INT, ex:[1, 3, 4])
  (branch_name_en:TEXT, ex:[FahMai Siam, Bangkok Ratchada 9 HQ, FahMai Chiang Mai Maya])
  (branch_type:TEXT, ex:[hq, branch, remote])
  (customer_type:TEXT, ex:[B2C, B2B])
  (customer_region:TEXT, ex:[BKK])
  (loyalty_tier:TEXT, ex:[silver, none, gold])
  (account_manager_id:TEXT, ex:[EMP-L3-00002])
]

# Table: v_sales_items
[
  (line_item_id:TEXT, PK, ex:[1000001286164, 1000001591146, 10000045503])
  (business_event_date:DATE, ex:[2024-01-01, 2024-01-02, 2024-01-03])
  (posting_date:DATE, ex:[2024-01-01, 2024-01-02, 2024-01-03])
  (effective_date:DATE)
  (as_of_date:DATE, ex:[2026-01-15])
  (txn_id:TEXT, -> v_sales.txn_id, ex:[TXN-202401-01000002, TXN-202401-01000422, TXN-202401-01000462])
  (sku_id:TEXT, -> dim_product.sku_id, ex:[AW-MN-001, DN-LT-010, NT-LT-001])
  (quantity:INT, ex:[1])
  (unit_price_thb:NUMERIC(14,2), ex:[4900.00, 5900.00, 6900.00])
  (line_discount_thb:NUMERIC(14,2), ex:[0.00])
  (line_total_thb:NUMERIC(14,2), ex:[4900.00, 5900.00, 6900.00])
  (is_care_plus:BOOL, ex:[False])
  (pos_log_line_id:TEXT, ex:[pos_BKK-CTW_20240101.tsv:line10, pos_BKK-CTW_20240101.tsv:line11, pos_BKK-CTW_20240101.tsv:line12])
  (brand_family:TEXT, ex:[ArcWave, Dawn, FahMai])
  (category:TEXT, ex:[laptop, monitor, smartphone])
  (subcategory:TEXT, ex:[flagship, midrange])
  (msrp_thb:NUMERIC(14,2), ex:[4900.00, 5900.00, 6900.00])
  (product_vendor_id:TEXT, ex:[V-001, V-002])
  (branch_code:TEXT, ex:[BKK-CTW, BKK-EMSP, BKK-PKT])
  (customer_id:TEXT, ex:[CUST-L3-000001, CUST-L3-000002, CUST-L3-000003])
  (is_b2b:BOOL, ex:[False, True])
  (promo_campaign_id:TEXT, ex:[CLEAR-EOY-2567, CLEAR-EOY-2568, MEGA-1111-2567])
  (fiscal_year_ce:INT, ex:[2024, 2025])
  (fiscal_quarter:INT, ex:[1, 2, 3])
]

# Table: v_returns
[
  (return_id:TEXT, PK, ex:[RET-202401-01003586, RET-202401-01006864, RET-202401-01009523])
  (business_event_date:DATE, ex:[2024-01-01, 2024-01-02, 2024-01-03])
  (posting_date:DATE, ex:[2025-11-24, 2025-03-31, 2025-02-16])
  (effective_date:DATE)
  (as_of_date:DATE, ex:[2026-01-15])
  (original_txn_id:TEXT, -> v_sales.txn_id, ex:[TXN-202507-24005955, TXN-202406-21011459, TXN-202502-24011840])
  (line_item_id:TEXT, ex:[934129273956, 310616972004, 663010055850])
  (sku_id:TEXT, -> dim_product.sku_id, ex:[SKU-MASS-091, SKU-MASS-101, SKU-MASS-098])
  (branch_code:TEXT, ex:[BKK-PKT, KKC-CTRL, CNX-MAYA])
  (customer_id:TEXT, -> dim_customer.customer_id, ex:[CUST-L3-000002, CUST-L3-000004, CUST-L3-000005])
  (return_reason:TEXT, ex:[customer_change_of_mind, hardware batch defect — WK-SW-004 Watch …, vendor recall — V-002 NovaTech battery])
  (approved_by_employee_id:TEXT, ex:[EMP-L3-00010, EMP-L3-00005])
  (days_since_purchase:TEXT, ex:[180, 0, 10])
  (return_amount_thb:NUMERIC(14,2), ex:[6900.00, 4900.00, 29900.00])
  (refund_id:TEXT, ex:[RFD-202506-09024674, RFD-202508-13011745, RFD-202506-12024952])
  (refund_amount_thb:NUMERIC(14,2), ex:[6900.00, 4900.00, 55900.00])
  (refund_approver_id:TEXT, ex:[EMP-L3-00005])
  (refund_cosig_id:TEXT)
  (brand_family:TEXT, ex:[Dawn, NovaTech, ArcWave])
  (category:TEXT, ex:[laptop, smartwatch, monitor])
  (branch_name_en:TEXT, ex:[FahMai Siam, Bangkok Ratchada 9 HQ, FahMai Chiang Mai Maya])
  (customer_type:TEXT, ex:[B2C])
  (fiscal_year_ce:INT, ex:[2024, 2025])
]

# Table: v_refunds
[
  (refund_id:TEXT, PK, ex:[RFD-202506-09024674, RFD-202508-13011745, RFD-202506-12024952])
  (business_event_date:DATE, ex:[2025-11-24, 2025-03-31, 2025-02-16])
  (posting_date:DATE, ex:[2025-11-24, 2025-03-31, 2025-02-16])
  (effective_date:DATE)
  (as_of_date:DATE, ex:[2026-01-15])
  (return_id:TEXT, ex:[RET-202401-01003586, RET-202401-01006864, RET-202401-01009523])
  (cs_interaction_id:TEXT)
  (customer_id:TEXT, ex:[CUST-L3-013470, CUST-L3-011021, CUST-L3-028184])
  (refund_amount_thb:NUMERIC(14,2), ex:[6900.00, 55900.00, 5900.00])
  (request_date:DATE, ex:[2025-11-24, 2025-03-31, 2025-02-16])
  (approver_employee_id:TEXT, -> dim_employee.employee_id, ex:[EMP-L3-00008, EMP-L3-00005, EMP-L3-00010])
  (cosig_employee_id:TEXT)
  (bank_txn_id:TEXT, ex:[BT-202405-458443321832, BT-202408-869822380279, BT-202508-253768508170])
  (approver_first_en:TEXT, ex:[Fin, May, Ollie])
  (approver_last_en:TEXT, ex:[Approver, Support, Logistics])
  (approver_position_level:TEXT, ex:[Manager, IC])
  (approver_dept_code:TEXT, ex:[OPS, SUP, FIN])
  (approver_position_title:TEXT)
  (customer_type:TEXT, ex:[B2C])
  (fiscal_year_ce:INT, ex:[2024, 2025])
]

# Table: v_warranty
[
  (claim_id:TEXT, PK, ex:[WC-202508-18020754, WC-202409-21012949, WC-202409-22003292])
  (business_event_date:DATE, ex:[2025-11-24, 2025-03-31, 2025-02-16])
  (posting_date:DATE, ex:[2025-11-24, 2025-03-31, 2025-02-16])
  (effective_date:DATE)
  (as_of_date:DATE, ex:[2026-01-15])
  (customer_id:TEXT, -> dim_customer.customer_id, ex:[CUST-L3-000011, CUST-L3-000013, CUST-L3-000014])
  (sku_id:TEXT, -> dim_product.sku_id, ex:[SKU-MASS-091, SKU-MASS-101, SKU-MASS-098])
  (original_txn_id:TEXT, ex:[TXN-202404-18023274, TXN-202411-24020559, TXN-202508-26010449])
  (claim_reason:TEXT, ex:[defect, vendor batch defect (V-004-MON-BATCH-256…, battery swelling concern — NT-LT-001 (pr…])
  (claim_amount_thb:NUMERIC(14,2), ex:[16900.00])
  (routing_destination:TEXT, ex:[novatech_service, fahmai_cs])
  (resolution_type:TEXT, ex:[pending, approved])
  (brand_family:TEXT, ex:[Dawn, NovaTech, ArcWave])
  (category:TEXT, ex:[smartwatch, laptop, monitor])
  (msrp_thb:NUMERIC(14,2), ex:[6900.00, 4900.00, 29900.00])
  (warranty_months:INT, ex:[12, 36, 24])
  (customer_type:TEXT, ex:[B2C])
  (fiscal_year_ce:INT, ex:[2024, 2025])
]

# Table: v_inventory
[
  (movement_id:TEXT, PK, ex:[1, 10, 100])
  (business_event_date:DATE, ex:[2024-01-01, 2024-01-02, 2024-01-03])
  (posting_date:DATE, ex:[2024-01-01, 2024-01-02, 2024-01-03])
  (effective_date:DATE)
  (as_of_date:DATE, ex:[2026-01-15])
  (sku_id:TEXT, ex:[AW-MN-001, DN-LT-010, NT-LT-001])
  (branch_code:TEXT, ex:[BKK-CTW, BKK-EMSP, BKK-PKT])
  (movement_type:TEXT, ex:[opening_balance, sale, transfer_in])
  (quantity:INT, ex:[-50, -1, 50])
  (related_txn_id:TEXT, ex:[TXN-202401-01000002, TXN-202401-01000422, TXN-202401-01000462])
  (brand_family:TEXT, ex:[ArcWave, Dawn, FahMai])
  (category:TEXT, ex:[laptop, monitor, smartphone])
  (end_of_life_date:DATE)
  (branch_name_en:TEXT, ex:[Bangkok Ratchada 9 HQ, FahMai Central World, FahMai Chiang Mai Maya])
  (fiscal_year_ce:INT, ex:[2024, 2025])
]

# Table: v_inventory_snapshot
[
  (snapshot_id:TEXT, PK, ex:[364662942755, 681438445098, 728897013577])
  (business_event_date:DATE, ex:[2025-02-28, 2025-05-31, 2024-09-30])
  (posting_date:DATE, ex:[2025-02-28, 2025-05-31, 2024-09-30])
  (effective_date:DATE)
  (as_of_date:DATE, ex:[2026-01-15])
  (month_end_date:DATE, ex:[2025-02-28, 2025-05-31, 2024-09-30])
  (sku_id:TEXT, ex:[SKU-MASS-091, SKU-MASS-101, SKU-MASS-098])
  (branch_code:TEXT, ex:[BKK-PKT, KKC-CTRL, CNX-MAYA])
  (closing_units:INT, ex:[652, 273, 51])
  (brand_family:TEXT, ex:[Dawn, NovaTech, ArcWave])
  (category:TEXT, ex:[smartwatch, laptop, monitor])
  (end_of_life_date:DATE)
  (branch_name_en:TEXT, ex:[FahMai Siam, Bangkok Ratchada 9 HQ, FahMai Chiang Mai Maya])
]

# Table: v_loyalty
[
  (ledger_id:TEXT, PK, ex:[1029183803070, 895078830828, 598817681684])
  (business_event_date:DATE, ex:[2024-01-01, 2024-01-02, 2024-01-03])
  (posting_date:DATE, ex:[2024-01-01, 2024-01-02, 2024-01-03])
  (effective_date:DATE)
  (as_of_date:DATE, ex:[2026-01-15])
  (customer_id:TEXT, ex:[CUST-L3-000001, CUST-L3-000002, CUST-L3-000004])
  (txn_id:TEXT, ex:[TXN-202403-20001253, TXN-202408-19007509, TXN-202406-13001641])
  (event_type:TEXT, ex:[earned, expired, redeemed])
  (points_delta:INT, ex:[-6246, -6110, -5738])
  (resulting_balance_points:INT, ex:[1489, 4790, 273])
  (resulting_tier:TEXT, ex:[gold, none, platinum])
  (customer_type:TEXT, ex:[B2C])
  (current_tier:TEXT, ex:[gold, platinum, silver])
  (region:TEXT, ex:[BKK])
]

# Table: v_promo  (phantom dup rows share txn_id across channel — dedup by txn_id for 'real' count)
[
  (redemption_id:TEXT, PK, ex:[1019597839275, 94666346226, 525891077361])
  (business_event_date:DATE, ex:[2025-07-31, 2025-11-11, 2024-12-12])
  (posting_date:DATE, ex:[2025-07-31, 2025-11-11, 2024-12-12])
  (effective_date:DATE)
  (as_of_date:DATE, ex:[2026-01-15])
  (txn_id:TEXT, ex:[TXN-202411-11000142, TXN-202411-11000842, TXN-202411-11001718])
  (customer_id:TEXT, ex:[CUST-L3-022848, CUST-L3-022862, CUST-L3-014972])
  (campaign_id:TEXT, ex:[CLEAR-EOY-2567, CLEAR-EOY-2568, MEGA-1111-2567])
  (discount_applied_thb:NUMERIC(14,2), ex:[5364.00, 10320.00, 4932.00])
  (channel:TEXT, ex:[offline, app, online])
  (description_en:TEXT)
  (start_timestamp:TIMESTAMP, ex:[2025-12-19 17:00:00+00:00, 2024-12-11 17:00:00+00:00, 2024-12-19 17:00:00+00:00])
  (end_timestamp:TIMESTAMP, ex:[2025-12-31 16:59:59+00:00, 2025-11-12 16:59:59+00:00, 2024-11-12 16:59:59+00:00])
  (discount_type:TEXT, ex:[pct_off, point_multiplier])
  (discount_value:NUMERIC, ex:[0.3000, 0.2000, 0.1200])
  (point_multiplier:NUMERIC, ex:[2.00])
]

# Table: v_vendor_payments
[
  (payment_id:TEXT, PK, ex:[VP-202509-817251, VP-202406-14314083, VP-202504-4671869])
  (business_event_date:DATE, ex:[2025-07-31, 2024-06-30, 2025-04-30])
  (posting_date:DATE, ex:[2024-02-28, 2025-05-08, 2025-09-01])
  (effective_date:DATE)
  (as_of_date:DATE, ex:[2026-01-15])
  (vendor_id:TEXT, -> dim_vendor.vendor_id, ex:[V-001, V-006, V-013])
  (vendor_invoice_id:TEXT, ex:[L2-MC-2024-10-15, L2-MC-2024-12-03, L2-MC-2025-01-22])
  (invoice_period_start:DATE, ex:[2025-03-11, 2024-11-22, 2024-06-01])
  (invoice_period_end:DATE, ex:[2025-07-31, 2024-06-30, 2025-04-30])
  (paid_amount_thb:NUMERIC(14,2), ex:[55000.00, 104500.00, 52500.00])
  (vendor_contract_version_id:TEXT, -> dim_vendor_contract_version.contract_version_id, ex:[1, 10, 11])
  (request_date:DATE, ex:[2024-02-28, 2025-05-08, 2025-09-01])
  (signing_employee_id:TEXT, ex:[EMP-L3-00005, EMP-L3-00008])
  (cosig_employee_id:TEXT, ex:[EMP-L3-00001])
  (bank_txn_id:TEXT, ex:[BT-202509-875909554465, BT-202510-466334837463, BT-202508-431420283161])
  (vendor_name_en:TEXT, ex:[VeloShip, PayWise, NovaTech])
  (vendor_category:TEXT, ex:[consumer_brand, logistics, payments])
  (contract_version_number:INT, ex:[3, 4, 2])
  (amendment_summary:TEXT)
]

# Table: v_bank_txn
[
  (bank_txn_id:TEXT, PK, ex:[BT-202401-1001612189611, BT-202401-1001773818030, BT-202401-100288086373])
  (business_event_date:DATE, ex:[2024-01-01, 2024-01-02, 2024-01-03])
  (posting_date:DATE, ex:[2025-11-24, 2025-03-31, 2025-02-16])
  (effective_date:DATE)
  (as_of_date:DATE, ex:[2026-01-15])
  (account_id:TEXT, ex:[BBL-OPER, KBANK-OPER, OPER-BKK-CTW])
  (transaction_type:TEXT, ex:[fee, transfer, deposit])
  (counterparty:TEXT, ex:[CUST-L3-002842, CUST-L3-029258, CUST-L3-024730])
  (related_entity_id:TEXT, ex:[1000243805828, 100024549842, 1000357467770])
  (related_entity_table:TEXT, ex:[FACT_PAYROLL, FACT_SALES_DEPOSIT_BATCH, FACT_REFUND_PAID])
  (amount_thb:NUMERIC(14,2), ex:[239600.00, 379900.00, 403900.00])
  (balance_after_thb:NUMERIC(14,2), ex:[958303550.00, 1284201800.00, 291625433.00])
  (description:TEXT)
  (bank:TEXT, ex:[BBL, KBank, SCB])
  (account_role:TEXT, ex:[operating])
  (associated_branch_code:TEXT, ex:[CNX-MAYA, BKK-CTW, HKT-FEST])
]

# Table: v_payroll
[
  (payroll_id:TEXT, PK, ex:[511708253693, 816637459373, 799478610278])
  (business_event_date:DATE, ex:[2025-02-28, 2025-05-31, 2024-09-30])
  (posting_date:DATE, ex:[2025-02-28, 2025-05-31, 2024-09-30])
  (effective_date:DATE)
  (as_of_date:DATE, ex:[2026-01-15])
  (employee_id:TEXT, ex:[EMP-L3-00007, EMP-L3-00393, EMP-L3-00148])
  (pay_period_start:DATE, ex:[2024-08-01, 2025-05-01, 2024-12-01])
  (pay_period_end:DATE, ex:[2025-02-28, 2025-05-31, 2024-09-30])
  (gross_pay_thb:NUMERIC(14,2), ex:[42000.00])
  (tax_deduction_thb:NUMERIC(14,2), ex:[2100.00])
  (social_security_thb:NUMERIC(14,2), ex:[750.00])
  (net_pay_thb:NUMERIC(14,2), ex:[39150.00])
  (bank_txn_id:TEXT, ex:[BT-202504-817930517378, BT-202405-141313105344, BT-202401-928642940954])
  (employment_status_at_period_end:TEXT, ex:[active])
  (first_name_en:TEXT, ex:[Staff037, Staff330, Staff149])
  (last_name_en:TEXT, ex:[Approver, Lead, Chairman])
  (dept_code:TEXT, ex:[CEO, HR, RET])
  (position_level:TEXT, ex:[Director, Manager, C-level])
  (branch_code:TEXT, ex:[BKK-R9])
  (position_title:TEXT)
]

# Table: v_cs
[
  (cs_interaction_id:TEXT, PK, ex:[CSI-202512-9158100, CSI-202504-2111470, CSI-202505-2026965])
  (business_event_date:DATE, ex:[2025-11-24, 2025-03-31, 2025-02-16])
  (posting_date:DATE, ex:[2025-11-24, 2025-03-31, 2025-02-16])
  (effective_date:DATE)
  (as_of_date:DATE, ex:[2026-01-15])
  (customer_id:TEXT, ex:[CUST-L3-000005, CUST-L3-000009, CUST-L3-000014])
  (employee_id:TEXT, ex:[EMP-L3-00175, EMP-L3-00049, EMP-L3-00061])
  (branch_code:TEXT, ex:[BKK-R9])
  (channel:TEXT, ex:[line_oa, in_person])
  (interaction_type:TEXT, ex:[warranty_claim, refund_request, chat_general])
  (resolution_type:TEXT, ex:[resolved, open])
  (related_refund_id:TEXT, ex:[RFD-202506-09024674, RFD-202508-13011745, RFD-202506-12024952])
  (related_warranty_claim_id:TEXT, ex:[WC-202508-18020754, WC-202409-21012949, WC-202409-22003292])
  (chat_session_id:TEXT, ex:[CHAT-LO-2025-11-12-0129d9, CHAT-LO-2024-02-13-95b917, CHAT-LO-2025-08-19-daee96])
  (emp_first_en:TEXT, ex:[Staff037, Staff187, Staff109])
  (emp_last_en:TEXT, ex:[Support, Member])
  (emp_dept_code:TEXT, ex:[SUP])
  (customer_type:TEXT, ex:[B2C])
  (branch_name_en:TEXT, ex:[Bangkok Ratchada 9 HQ])
]

# Table: v_shipping
[
  (shipping_id:TEXT, PK, ex:[1013251693941, 459904380594, 790070558102])
  (business_event_date:DATE, ex:[2024-01-01, 2024-01-02, 2024-01-03])
  (posting_date:DATE, ex:[2025-11-24, 2025-03-31, 2025-02-16])
  (effective_date:DATE)
  (as_of_date:DATE, ex:[2026-01-15])
  (txn_id:TEXT, ex:[TXN-202407-27025700, TXN-202505-08011413, TXN-202510-27020196])
  (vendor_id:TEXT, ex:[V-006])
  (tracking_number:TEXT)
  (origin_branch_code:TEXT, ex:[BKK-PKT, KKC-CTRL, CNX-MAYA])
  (destination_province:TEXT, ex:[Chiang Mai, Khon Kaen, Bangkok])
  (confirmation_status:TEXT, ex:[shipped])
  (vendor_name_en:TEXT, ex:[VeloShip])
  (origin_branch_name_en:TEXT, ex:[FahMai Siam, Bangkok Ratchada 9 HQ, FahMai Chiang Mai Maya])
]

# Table: dim_product
[
  (sku_id:TEXT, PK, ex:[SKU-MASS-091, SKU-MASS-101, SKU-MASS-098])
  (brand_family:TEXT, ex:[Dawn, NovaTech, ArcWave])
  (dept_code:TEXT, ex:[SF])
  (category:TEXT, ex:[smartwatch, laptop, monitor])
  (subcategory:TEXT, ex:[flagship, midrange])
  (msrp_thb:NUMERIC(14,2), ex:[6900.00, 4900.00, 29900.00])
  (msrp_tier:TEXT, ex:[>=30K, <10K, 10K-30K])
  (is_third_party:BOOL, ex:[False, True])
  (vendor_id:TEXT, -> dim_vendor.vendor_id, ex:[V-001, V-002])
  (launch_date:DATE, ex:[2023-01-01, 2024-01-01, 2025-07-15])
  (end_of_life_date:DATE)
  (warranty_months:INT, ex:[12, 36, 24])
  (care_plus_eligible:BOOL, ex:[False, True])
]

# Table: dim_customer
[
  (customer_id:TEXT, PK, ex:[CUST-L3-008919, CUST-L3-017466, CUST-L3-019983])
  (first_name_th:TEXT, ex:[นริศ, เกษม, ขวัญใจ])
  (last_name_th:TEXT, ex:[มหาเปียร, ศรีวรรณ, วรากร])
  (first_name_en:TEXT, ex:[B2B Customer 013600, B2B Customer 013400, B2B Customer 028800])
  (last_name_en:TEXT, ex:[Srisawat, Phiphat, Chanphen])
  (email:TEXT, ex:[customer029805@example.test, customer007268@example.test, customer018231@example.test])
  (phone:TEXT, ex:[0800003722, 0800019551, 0800011261])
  (province:TEXT, ex:[Bangkok])
  (region:TEXT, ex:[BKK])
  (age:INT, ex:[64, 62, 55])
  (gender:TEXT, ex:[M, F])
  (signup_date:DATE, ex:[2024-02-01, 2024-01-05])
  (customer_type:TEXT, ex:[B2B, B2C])
  (b2b_subtype:TEXT, ex:[Enterprise, SME])
  (account_manager_id:TEXT, ex:[EMP-L3-00002])
  (payment_terms:TEXT, ex:[NET-30, NET-60])
  (loyalty_tier:TEXT, ex:[gold, none, platinum])
  (channel_pref:TEXT, ex:[offline, mixed])
  (uses_line_oa:BOOL, ex:[False, True])
]

# Table: dim_employee
[
  (employee_id:TEXT, PK, ex:[EMP-L3-00007, EMP-L3-00393, EMP-L3-00148])
  (first_name_th:TEXT, ex:[Staff037, Staff330, Staff149])
  (last_name_th:TEXT, ex:[Approver, Lead, Chairman])
  (first_name_en:TEXT, ex:[Staff037, Staff330, Staff149])
  (last_name_en:TEXT, ex:[Approver, Lead, Chairman])
  (email:TEXT, ex:[staff518.m@fahmai.co.th, staff207.m@fahmai.co.th, vichai.l@fahmai.co.th])
  (phone:TEXT)
  (branch_code:TEXT, ex:[BKK-R9])
  (dept_code:TEXT, ex:[B2B, CEO, FIN])
  (section:TEXT)
  (unit:TEXT)
  (position_title:TEXT)
  (position_level:TEXT, ex:[C-level, Director, IC])
  (reports_to_employee_id:TEXT, ex:[EMP-L3-00003, EMP-L3-00002, EMP-L3-00004])
  (hire_date:DATE, ex:[2023-01-01])
  (termination_date:DATE)
  (termination_reason:TEXT)
  (status:TEXT, ex:[active])
  (employment_type:TEXT, ex:[FT])
  (is_canon_leader:BOOL, ex:[False, True])
  (canon_role_label:TEXT, ex:[Board Chair, Founder & CEO, Incoming CEO])
]

# Table: dim_branch
[
  (branch_code:TEXT, PK, ex:[CNX-MAYA, BKK-CTW, HKT-FEST])
  (name_th:TEXT, ex:[FahMai Siam, FahMai Chiang Mai Maya, FahMai Phuket Festival])
  (name_en:TEXT, ex:[FahMai Siam, Bangkok Ratchada 9 HQ, FahMai Chiang Mai Maya])
  (branch_type:TEXT, ex:[hq, branch, remote])
  (is_service_center:BOOL, ex:[False, True])
  (retail_floor_coefficient:NUMERIC, ex:[0.90, 1.00, 0.20])
  (traffic_share_pct:NUMERIC, ex:[0.06, 0.12, 0.07])
  (employee_headcount_share_pct:NUMERIC, ex:[0.06, 0.04, 0.20])
]

# Table: dim_vendor
[
  (vendor_id:TEXT, PK, ex:[V-006, V-001, V-002])
  (name_th:TEXT, ex:[VeloShip, PayWise, NovaTech])
  (name_en:TEXT, ex:[VeloShip, PayWise, NovaTech])
  (category:TEXT, ex:[consumer_brand, logistics, payments])
  (role:TEXT, ex:[partner_brand, processor, warranty_partner])
  (payment_terms:TEXT, ex:[NET-30, NET-15])
  (invoice_cadence:TEXT, ex:[weekly, monthly])
  (is_partner_brand:BOOL, ex:[False, True])
  (is_component_supplier:BOOL, ex:[False])
  (start_date:DATE, ex:[2023-01-01, 2025-04-01])
  (end_date:DATE, ex:[2025-03-31])
]

# Table: dim_date  (fiscal_year is BUDDHIST ERA; use fiscal_year_ce for CE)
[
  (date_iso:DATE, PK, ex:[2025-11-24, 2025-03-31, 2025-02-16])
  (date_be_string:TEXT, ex:[2568-04-11, 2568-01-04, 2568-03-02])
  (day_of_week:INT, ex:[7, 1, 5])
  (is_thai_public_holiday:BOOL, ex:[False])
  (holiday_name:TEXT)
  (fiscal_year:INT, ex:[2568, 2567])
  (fiscal_quarter:INT, ex:[1, 3, 4])
  (fiscal_year_ce:INT, ex:[2024, 2025])
]

# Table: dim_policy_version  (as-of: effective_date<=D AND (end_date IS NULL OR end_date>D))
[
  (policy_version_id:TEXT, PK, ex:[2, 9, 4])
  (policy_class:TEXT, ex:[shipping, return, warranty])
  (policy_variable:TEXT, ex:[free_shipping_threshold_thb, care_plus_sku_tier_table, refund_threshold_thb])
  (scope_filter:TEXT, ex:[global])
  (value_numeric:NUMERIC, ex:[2000, 14, 0.0125])
  (value_text:TEXT, ex:[novatech_service])
  (policy_value_table_ref:TEXT, ex:[dim_signing_authority_ladder, dim_care_plus_sku_tier])
  (effective_date:DATE, ex:[2025-03-01, 2025-05-01, 2025-02-15])
  (end_date:DATE, ex:[2025-03-01, 2025-02-15, 2025-04-01])
  (policy_doc_filename:TEXT)
]

# Table: dim_signing_authority_ladder
[
  (ladder_row_id:TEXT, PK, ex:[2, 4, 7])
  (policy_version_id:TEXT, -> dim_policy_version.policy_version_id, ex:[6, 5])
  (position_level_code:TEXT, ex:[Director, Manager, C-level])
  (dept_code:TEXT, ex:[SUP])
  (amount_ceiling_thb:NUMERIC(14,2), ex:[5000000.00, 500000.00, 100000.00])
  (min_co_signers:INT, ex:[0, 1])
  (co_signer_min_position_level_code:TEXT, ex:[Manager])
  (description_th:TEXT)
]

# Table: dim_vendor_contract_version
[
  (contract_version_id:TEXT, PK, ex:[13, 18, 2])
  (vendor_id:TEXT, ex:[V-006, V-001, V-002])
  (version_number:INT, ex:[3, 4, 2])
  (effective_date:DATE, ex:[2024-07-01, 2025-12-01, 2025-08-01])
  (end_date:DATE, ex:[2025-03-31, 2024-07-01, 2025-12-01])
  (contract_pdf_filename:TEXT, ex:[contracts/V-006-v1.pdf, contracts/V-001-v4.pdf, contracts/V-002-v2.pdf])
  (amendment_summary:TEXT)
]

# Table: dim_promo_campaign
[
  (campaign_id:TEXT, PK, ex:[MEGA-1111-2567, MEGA-1111-2568, CLEAR-EOY-2568])
  (start_timestamp:TIMESTAMP, ex:[2025-12-19 17:00:00+00:00, 2024-12-11 17:00:00+00:00, 2024-12-19 17:00:00+00:00])
  (end_timestamp:TIMESTAMP, ex:[2025-12-31 16:59:59+00:00, 2025-11-12 16:59:59+00:00, 2024-11-12 16:59:59+00:00])
  (scope_filter:TEXT, ex:[sku-list:[DN-LT-010,WK-SW-004,AW-MN-001], all, sku-list:[SF-Galaxy-Pro-2568]])
  (description_th:TEXT)
  (description_en:TEXT)
]

# Table: dim_promo_mechanic
[
  (promo_mechanic_id:TEXT, PK, ex:[2, 4, 7])
  (campaign_id:TEXT, -> dim_promo_campaign.campaign_id, ex:[MEGA-1111-2567, MEGA-1111-2568, CLEAR-EOY-2568])
  (discount_type:TEXT, ex:[pct_off, point_multiplier])
  (discount_value:NUMERIC, ex:[0.3000, 0.2000, 0.1200])
  (point_multiplier:NUMERIC, ex:[2.00])
  (min_basket_thb:NUMERIC(14,2))
  (description_th:TEXT)
]

# Table: dim_product_recall_history
[
  (history_id:TEXT, PK, ex:[2, 3, 1])
  (sku_id:TEXT, -> dim_product.sku_id, ex:[NT-LT-001])
  (status:TEXT, ex:[active, completed, normal])
  (transition_date:DATE, ex:[2025-10-15, 2025-09-10, 2024-01-01])
]

# Table: dim_bank_account
[
  (account_id:TEXT, PK, ex:[OPER-BKK-PKT, OPER-BKK-R9, KBANK-OPER])
  (bank:TEXT, ex:[BBL, KBank, SCB])
  (account_number:TEXT, ex:[108-3-10008-9, 002-1-00001-2, 003-1-00001-3])
  (account_role:TEXT, ex:[operating])
  (associated_branch_code:TEXT, ex:[CNX-MAYA, BKK-CTW, HKT-FEST])
  (currency:TEXT, ex:[THB])
  (opening_balance_thb:NUMERIC(14,2), ex:[5000000.00, 1000000.00, 3000000.00])
  (statement_cadence:TEXT, ex:[monthly])
]

# Table: dim_department
[
  (dept_code:TEXT, PK, ex:[SUP, OPS, CEO])
  (dept_name_th:TEXT, ex:[Marketing, Operations, Finance])
  (dept_name_en:TEXT, ex:[Marketing, Operations, Finance])
  (dept_type:TEXT, ex:[corporate, product_division])
]

# Table: dim_position_level
[
  (position_level_code:TEXT, PK, ex:[Director, Manager, VP])
  (rank:INT, ex:[3, 5, 4])
  (default_signing_authority_thb:NUMERIC(14,2), ex:[25000.00, 5000000.00, 1000000.00])
]

# Table: dim_care_plus_sku_tier
[
  (tier_row_id:TEXT, ex:[2, 1])
  (policy_version_id:TEXT, ex:[7])
  (sku_id:TEXT, ex:[SF-Galaxy-Pro-2568, NT-LT-001])
  (sku_category:TEXT)
  (care_plus_price_thb:NUMERIC(14,2), ex:[3990.00, 3490.00])
  (coverage_months:INT, ex:[36, 24])
  (description_th:TEXT)
]

# Table: pos_logs  (BKK-CTW only; v1->v2 cutover 2025-04-01 (discount_amt -> discount_total_thb))
[
  (timestamp:TEXT, ex:[2025-09-17T08:48:52+07:00, 2025-08-30T14:31:56+07:00, 2025-08-04T12:39:20+07:00])
  (branch_code:TEXT, ex:[BKK-CTW])
  (txn_id:TEXT, ex:[TXN-202410-15001105, TXN-202506-09023726, TXN-202502-05009978])
  (line_seq:INT, ex:[7, 1, 5])
  (sku_id:TEXT, ex:[SKU-MASS-091, SKU-MASS-101, SKU-MASS-098])
  (quantity:INT, ex:[1])
  (unit_price_thb:NUMERIC(14,2), ex:[6900.00, 29900.00, 4900.00])
  (discount_amt:NUMERIC(14,2), ex:[0.00])
  (payment_method:TEXT, ex:[cash, mobile_wallet, debit_card])
  (schema_version:INT, ex:[1, 2])
  (source_file:TEXT, ex:[pos_BKK-CTW_20251216.tsv, pos_BKK-CTW_20240831.tsv, pos_BKK-CTW_20241015.tsv])
  (payment_terminal_id:TEXT, ex:[BKK-CTW-POS-01, BKK-CTW-POS-02, BKK-CTW-POS-03])
  (discount_total_thb:NUMERIC(14,2), ex:[0.00])
  (loyalty_tier_at_purchase:TEXT, ex:[none])
]

# Table: ocr_warranty_form  (OCR of warranty_form PNGs; claim_id_db joins fact_warranty_claim.claim_id)
[
  (artifact_id:TEXT, PK, ex:[WC-SKU-MASS-073-202507-09006474, WC-SKU-MASS-075-202508-26001216, WC-SKU-MASS-011-202409-03021472])
  (claim_id_db:TEXT, -> v_warranty.claim_id (= fact_warranty_claim.claim_id), ex:[WC-202412-20021642, WC-202511-03014523, WC-202411-26012249])
  (claim_id:TEXT, ex:[WC-2567-08-11023415, WC-2568-04-01028123, WC-2567-05-16002795])
  (business_event_date:DATE, ex:[2025-11-24, 2025-02-16, 2025-05-22])
  (business_event_date_be:TEXT, ex:[31/12/2567, 14/06/2567, 29/05/2568])
  (customer_id:TEXT, ex:[CUST-L3-011844, CUST-L3-006136, CUST-L3-017605])
  (sku_id:TEXT, ex:[SKU-MASS-091, SKUMASS-104, SKU-MASS-101])
  (claim_reason:TEXT, ex:[defect])
  (claim_amount_thb:NUMERIC(14,2))
]

【Foreign keys】
v_sales.customer_id = dim_customer.customer_id
v_sales.branch_code = dim_branch.branch_code
v_sales.employee_id = dim_employee.employee_id
v_sales.promo_campaign_id = dim_promo_campaign.campaign_id
v_sales_items.sku_id = dim_product.sku_id
v_sales_items.txn_id = v_sales.txn_id
v_returns.sku_id = dim_product.sku_id
v_returns.customer_id = dim_customer.customer_id
v_returns.original_txn_id = v_sales.txn_id
v_warranty.sku_id = dim_product.sku_id
v_warranty.customer_id = dim_customer.customer_id
v_refunds.approver_employee_id = dim_employee.employee_id
v_vendor_payments.vendor_id = dim_vendor.vendor_id
v_vendor_payments.vendor_contract_version_id = dim_vendor_contract_version.contract_version_id
dim_product.vendor_id = dim_vendor.vendor_id
dim_signing_authority_ladder.policy_version_id = dim_policy_version.policy_version_id
dim_promo_mechanic.campaign_id = dim_promo_campaign.campaign_id
dim_product_recall_history.sku_id = dim_product.sku_id
ocr_warranty_form.claim_id_db = v_warranty.claim_id (= fact_warranty_claim.claim_id)

## Raw fact_* tables (no M-Schema block — each mirrors its v_* minus enrichment/dedup;
use only for data-quality / phantom / when a question names FACT_* explicitly):
fact_sales, fact_sales_line_item, fact_return, fact_refund_paid, fact_warranty_claim,
fact_promo_redemption, fact_inventory_movement, fact_inventory_monthly_snapshot,
fact_loyalty_ledger, fact_payroll, fact_cs_interaction, fact_shipping, fact_bank_transaction,
fact_vendor_payment, doc_corpus(doc_id, channel, doc_date, topic, content, ...)
'''
